language: php
php:
  - 5.3
  - 5.4
  - 5.5
env:
  - SYMFONY_VERSION="2.1.*"
  - SYMFONY_VERSION="2.2.*"
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"
  - SYMFONY_VERSION="2.5.*"
  - SYMFONY_VERSION="dev-master" MIN_STABILITY="dev"
before_script:
  - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - sh travis_before_build.sh
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
notifications:
  email:
    on_success: always
    on_failure: always
